# Generated by Django 3.2.15 on 2022-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0007_home_image_delete_bottom_4_delete_top_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='kategori',
            field=models.CharField(choices=[('Galeri', 'Galeri'), ('Mutfak', 'Mutfak'), ('Salon', 'Salon'), ('Banyo', 'Banyo'), ('Koridor', 'Koridor'), ('Ofis', 'Ofis')], max_length=50, null=True),
        ),
    ]
