# Generated by Django 4.1 on 2022-09-14 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0002_alter_contact_isim_alter_contact_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(choices=[('Banyo', 'Banyo'), ('Salon', 'Mutfak'), ('Banyo', 'Banyo'), ('Koridor', 'Koridor'), ('Ofis', 'Ofis')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(null=True, upload_to='image/')),
                ('mail', models.CharField(max_length=200, null=True)),
                ('telefon', models.CharField(max_length=200, null=True)),
                ('mesaj', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
