# Generated by Django 4.1 on 2022-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0004_delete_category_remove_gallery_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim1', models.ImageField(null=True, upload_to='image/')),
                ('resim2', models.ImageField(null=True, upload_to='image/')),
                ('resim3', models.ImageField(null=True, upload_to='image/')),
                ('resim4', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Top_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim1', models.ImageField(null=True, upload_to='image/')),
                ('resim2', models.ImageField(null=True, upload_to='image/')),
                ('resim3', models.ImageField(null=True, upload_to='image/')),
                ('resim4', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='kategori',
            field=models.CharField(choices=[('Mutfak', 'Mutfak'), ('Salon', 'Salon'), ('Banyo', 'Banyo'), ('Koridor', 'Koridor'), ('Ofis', 'Ofis')], max_length=50, null=True),
        ),
    ]
