# Generated by Django 4.1 on 2022-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0005_bottom_4_top_4_alter_gallery_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottom_4',
            name='resim4',
        ),
        migrations.AddField(
            model_name='bottom_4',
            name='name_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bottom_4',
            name='name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bottom_4',
            name='name_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bottom_4',
            name='name_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='top_4',
            name='name_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='top_4',
            name='name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='top_4',
            name='name_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='top_4',
            name='name_4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
