# Generated by Django 4.1 on 2022-09-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0006_remove_bottom_4_resim4_bottom_4_name_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=100, null=True)),
                ('resim1', models.ImageField(null=True, upload_to='image/')),
                ('name_2', models.CharField(max_length=100, null=True)),
                ('resim2', models.ImageField(null=True, upload_to='image/')),
                ('name_3', models.CharField(max_length=100, null=True)),
                ('resim3', models.ImageField(null=True, upload_to='image/')),
                ('name_4', models.CharField(max_length=100, null=True)),
                ('resim4', models.ImageField(null=True, upload_to='image/')),
                ('name_5', models.CharField(max_length=100, null=True)),
                ('resim5', models.ImageField(null=True, upload_to='image/')),
                ('name_6', models.CharField(max_length=100, null=True)),
                ('resim6', models.ImageField(null=True, upload_to='image/')),
                ('name_7', models.CharField(max_length=100, null=True)),
                ('resim7', models.ImageField(null=True, upload_to='image/')),
                ('name_8', models.CharField(max_length=100, null=True)),
                ('resim8', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Bottom_4',
        ),
        migrations.DeleteModel(
            name='Top_4',
        ),
    ]
